// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbmmGlcBz45OBDExT9FdxrnK6LvSRzMYQ',
    appId: '1:924051962604:web:fbc5f3106bcce405f0c3c9',
    messagingSenderId: '924051962604',
    projectId: 'mydown-876cf',
    authDomain: 'mydown-876cf.firebaseapp.com',
    storageBucket: 'mydown-876cf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEHCMDvsz4A8PumIpErR02cKbT84e5FD8',
    appId: '1:924051962604:android:e7ffee35b99a3126f0c3c9',
    messagingSenderId: '924051962604',
    projectId: 'mydown-876cf',
    storageBucket: 'mydown-876cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4LTwv_5dQ01_F18o-gwKUpVIbTAcYBqA',
    appId: '1:924051962604:ios:6fd13d804fdfa75df0c3c9',
    messagingSenderId: '924051962604',
    projectId: 'mydown-876cf',
    storageBucket: 'mydown-876cf.appspot.com',
    iosBundleId: 'com.example.myDownProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4LTwv_5dQ01_F18o-gwKUpVIbTAcYBqA',
    appId: '1:924051962604:ios:9974eece82fb36faf0c3c9',
    messagingSenderId: '924051962604',
    projectId: 'mydown-876cf',
    storageBucket: 'mydown-876cf.appspot.com',
    iosBundleId: 'com.example.myDownProject.RunnerTests',
  );
}
